mode = "fastest"

[light_sources]
	water_sensitive_check = false
	block_entities = false
	entities = false
	self = true
	tnt = "simple"
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				block_display = true
				chest_boat = true
				boat = true
				allay = true
				area_effect_cloud = true
				bat = true
				blaze = true
				camel = true
				cat = true
				cave_spider = true
				armor_stand = true
				player = true

